project:
    name: "my_custom_GPT"
    description: "A custom GPT model for text generation"
    version: "1.0.0"
    author: "Devesh176"

tokenizer:
    tokenizer_type: "BPE"
    tokenizer_vocab_path: "utils/bpe_vocab.json"
    tokenizer_merges_path: "utils/bpe_merges.txt"
    vocab_size: 50257 # same as gpt2 tokenzer
    embedding_dim: 768
    token_sequence_size: 256

data_load:
    batch_size: 64  # hyper parameters
    block_size: 64
    num_workers: 4
    stride: 1
    max_length: 128
    shuffle: True
    token_sequence_size: 256

GPT_CONFIG:
    model_name: "custom_gpt"
    model_type: "GPT"
    # optimizer: "AdamW"
    loss_function: "CrossEntropyLoss"
    scheduler: "CosineAnnealingLR"
    warmup_steps: 1000
    weight_decay: 0.01
    gradient_clip_val: 1.0
    save_checkpoint_every: 1000
    log_interval: 100
    emb_dim: 768
    n_heads: 12
    ff_hidden_dim: 1024
    ctx_length: 1024
    dropout: 0.1
    qkv_bias: False
    n_layers: 12
    device: "cuda"  # or "cpu"

TRAINING_CONFIG:
    optimizer: "AdamW"
    loss_function: "CrossEntropyLoss"
    num_epochs: 10
    batch_size: 1
    weight_decay: 0.1
    learning_rate: 5e-4
    eval_freq: 1
    eval_iter: 1
    train_ratio: 0.8
    num_workers: 4




