project:
    name: "my_custom_GPT"
    description: "A custom GPT model for text generation"
    version: "1.0.0"
    author: "Devesh176"

tokenizer:
    tokenizer_vocab_path: "utils/bpe_vocab.json"
    tokenizer_merges_path: "utils/bpe_merges.txt"
    vocab_size: 50257 # same as gpt2 tokenzer
    embedding_dim: 256
    token_sequence_size: 256

data_load:
    batch_size: 128  # hyper parameters
    block_size: 256
    num_workers: 4
    stride: 1
    max_length: 512
    shuffle: True

GPT_CONFIG:
    model_name: "custom_gpt"
    model_type: "GPT"
    tokenizer_type: "BPE"
    optimizer: "AdamW"
    loss_function: "CrossEntropyLoss"
    scheduler: "CosineAnnealingLR"
    warmup_steps: 1000
    weight_decay: 0.01
    gradient_clip_val: 1.0
    save_checkpoint_every: 1000
    log_interval: 100
    emb_dim: 256
    head_dim: 256
    n_heads: 8
    ctx_length: 256
    dropout: 0.1
    qkv_bias: True
    n_layers: 12
    device: "cuda"  # or "cpu"


